# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Gruber by Patel, Nimai &lt;nimai.m.patel@gmail.com&gt;, colors from www.github.com/rexim/gruber-darker-theme

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#181818"
idle_fg = "#f4f4ff"
info_bg = "#95a99f"
info_fg = "#181818"
good_bg = "#73c936"
good_fg = "#181818"
warning_bg = "#ffdd33"
warning_fg = "#181818"
critical_bg = "#f43841"
critical_fg = "#181818"
# The rest of the theme settings are left at default.
