# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Material Palenight by Nate Peterson

idle_bg = "#292d3e"
idle_fg = "#959dcb"
info_bg = "#89ddff"
info_fg = "#292d3e"
good_bg = "#c3e88d"
good_fg = "#292d3e"
warning_bg = "#ffcb6b"
warning_fg = "#292d3e"
critical_bg = "#f07178"
critical_fg = "#292d3e"
# The rest of the theme settings are left at default.
