# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Qualia by isaacwhanson

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#101010"
idle_fg = "#c0c0c0"
info_bg = "#c8c874"
info_fg = "#101010"
good_bg = "#80c990"
good_fg = "#101010"
warning_bg = "#e6a3dc"
warning_fg = "#101010"
critical_bg = "#efa6a2"
critical_fg = "#101010"
# The rest of the theme settings are left at default.
