# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Horizon Terminal Dark by Michaël Ball (http://github.com/michael-ball/)

idle_bg = "#1c1e26"
idle_fg = "#cbced0"
info_bg = "#59e1e3"
info_fg = "#1c1e26"
good_bg = "#29d398"
good_fg = "#1c1e26"
warning_bg = "#fac29a"
warning_fg = "#1c1e26"
critical_bg = "#e95678"
critical_fg = "#1c1e26"
# The rest of the theme settings are left at default.
