# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Classic Light by Jason Heeris (http://heeris.id.au)

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#f5f5f5"
idle_fg = "#303030"
info_bg = "#75b5aa"
info_fg = "#f5f5f5"
good_bg = "#90a959"
good_fg = "#f5f5f5"
warning_bg = "#f4bf75"
warning_fg = "#f5f5f5"
critical_bg = "#ac4142"
critical_fg = "#f5f5f5"
# The rest of the theme settings are left at default.
