# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Ashes by Jannik Siebert (https://github.com/janniks)

idle_bg = "#1c2023"
idle_fg = "#c7ccd1"
info_bg = "#95aec7"
info_fg = "#1c2023"
good_bg = "#95c7ae"
good_fg = "#1c2023"
warning_bg = "#aec795"
warning_fg = "#1c2023"
critical_bg = "#c7ae95"
critical_fg = "#1c2023"
# The rest of the theme settings are left at default.
