# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Material Darker by Nate Peterson

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#212121"
idle_fg = "#eeffff"
info_bg = "#89ddff"
info_fg = "#212121"
good_bg = "#c3e88d"
good_fg = "#212121"
warning_bg = "#ffcb6b"
warning_fg = "#212121"
critical_bg = "#f07178"
critical_fg = "#212121"
# The rest of the theme settings are left at default.
