# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Everforest Dark Hard by Sainnhe Park (https://github.com/sainnhe)

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#272e33"
idle_fg = "#d3c6aa"
info_bg = "#83c092"
info_fg = "#272e33"
good_bg = "#a7c080"
good_fg = "#272e33"
warning_bg = "#dbbc7f"
warning_fg = "#272e33"
critical_bg = "#e67e80"
critical_fg = "#272e33"
# The rest of the theme settings are left at default.
