# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Stella by Shrimpram

idle_bg = "#2b213c"
idle_fg = "#998bad"
info_bg = "#9bc7bf"
info_fg = "#2b213c"
good_bg = "#acc79b"
good_fg = "#2b213c"
warning_bg = "#c7c691"
warning_fg = "#2b213c"
critical_bg = "#c79987"
critical_fg = "#2b213c"
# The rest of the theme settings are left at default.
