# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Evenok Dark by Mekeor Melire

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#d0d0d0"
info_bg = "#00bab3"
info_fg = "#000000"
good_bg = "#54bc5c"
good_fg = "#000000"
warning_bg = "#b8a300"
warning_fg = "#000000"
critical_bg = "#f5708a"
critical_fg = "#000000"
# The rest of the theme settings are left at default.
