# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Nord by arcticicestudio

idle_bg = "#2e3440"
idle_fg = "#e5e9f0"
info_bg = "#88c0d0"
info_fg = "#2e3440"
good_bg = "#a3be8c"
good_fg = "#2e3440"
warning_bg = "#ebcb8b"
warning_fg = "#2e3440"
critical_bg = "#bf616a"
critical_fg = "#2e3440"
# The rest of the theme settings are left at default.
