# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# eris by ed (https://codeberg.org/ed)

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#0a0920"
idle_fg = "#606bac"
info_bg = "#258fc4"
info_fg = "#0a0920"
good_bg = "#faaea2"
good_fg = "#0a0920"
warning_bg = "#faaea2"
warning_fg = "#0a0920"
critical_bg = "#f768a3"
critical_fg = "#0a0920"
# The rest of the theme settings are left at default.
