# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# emil by limelier

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#efefef"
idle_fg = "#313145"
info_bg = "#2155d6"
info_fg = "#efefef"
good_bg = "#0073a8"
good_fg = "#efefef"
warning_bg = "#ff669b"
warning_fg = "#efefef"
critical_bg = "#f43979"
critical_fg = "#efefef"
# The rest of the theme settings are left at default.
