# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Catppuccin Mocha by https://github.com/catppuccin/catppuccin

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#1e1e2e"
idle_fg = "#cdd6f4"
info_bg = "#94e2d5"
info_fg = "#1e1e2e"
good_bg = "#a6e3a1"
good_fg = "#1e1e2e"
warning_bg = "#f9e2af"
warning_fg = "#1e1e2e"
critical_bg = "#f38ba8"
critical_fg = "#1e1e2e"
# The rest of the theme settings are left at default.
