# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Framer by Framer (Maintained by Jesse Hoyos)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#181818"
idle_fg = "#d0d0d0"
info_bg = "#acddfd"
info_fg = "#181818"
good_bg = "#32ccdc"
good_fg = "#181818"
warning_bg = "#fecb6e"
warning_fg = "#181818"
critical_bg = "#fd886b"
critical_fg = "#181818"
# The rest of the theme settings are left at default.
