# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Tokyodark Terminal by Tiagovla (https://github.com/tiagovla/)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#11121d"
idle_fg = "#a0a8cd"
info_bg = "#38a89d"
info_fg = "#11121d"
good_bg = "#95c561"
good_fg = "#11121d"
warning_bg = "#d7a65f"
warning_fg = "#11121d"
critical_bg = "#ee6d85"
critical_fg = "#11121d"
# The rest of the theme settings are left at default.
