# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Horizon Dark by Michaël Ball (http://github.com/michael-ball/)

idle_bg = "#1c1e26"
idle_fg = "#cbced0"
info_bg = "#24a8b4"
info_fg = "#1c1e26"
good_bg = "#efaf8e"
good_fg = "#1c1e26"
warning_bg = "#efb993"
warning_fg = "#1c1e26"
critical_bg = "#e93c58"
critical_fg = "#1c1e26"
# The rest of the theme settings are left at default.
