# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Apprentice by romainl

idle_bg = "#262626"
idle_fg = "#5f5f87"
info_bg = "#87afd7"
info_fg = "#262626"
good_bg = "#ffffaf"
good_fg = "#262626"
warning_bg = "#87af87"
warning_fg = "#262626"
critical_bg = "#444444"
critical_fg = "#262626"
# The rest of the theme settings are left at default.
