# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# XCode Dusk by Elsa Gonsiorowski (https://github.com/gonsie)

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#282b35"
idle_fg = "#939599"
info_bg = "#00a0be"
info_fg = "#282b35"
good_bg = "#df0002"
good_fg = "#282b35"
warning_bg = "#438288"
warning_fg = "#282b35"
critical_bg = "#b21889"
critical_fg = "#282b35"
# The rest of the theme settings are left at default.
