# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Flat by Chris Kempson (http://chriskempson.com)

idle_bg = "#2c3e50"
idle_fg = "#e0e0e0"
info_bg = "#1abc9c"
info_fg = "#2c3e50"
good_bg = "#2ecc71"
good_fg = "#2c3e50"
warning_bg = "#f1c40f"
warning_fg = "#2c3e50"
critical_bg = "#e74c3c"
critical_fg = "#2c3e50"
# The rest of the theme settings are left at default.
