# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Google Dark by Seth Wright (http://sethawright.com)

idle_bg = "#1d1f21"
idle_fg = "#c5c8c6"
info_bg = "#3971ed"
info_fg = "#1d1f21"
good_bg = "#198844"
good_fg = "#1d1f21"
warning_bg = "#fba922"
warning_fg = "#1d1f21"
critical_bg = "#cc342b"
critical_fg = "#1d1f21"
# The rest of the theme settings are left at default.
