# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# vice by Thomas Leon Highbaugh thighbaugh@zoho.com

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#17191e"
idle_fg = "#8b9cbe"
info_bg = "#8265ff"
info_fg = "#17191e"
good_bg = "#0badff"
good_fg = "#17191e"
warning_bg = "#f0ffaa"
warning_fg = "#17191e"
critical_bg = "#ff29a8"
critical_fg = "#17191e"
# The rest of the theme settings are left at default.
