# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Horizon Terminal Light by Michaël Ball (http://github.com/michael-ball/)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#fdf0ed"
idle_fg = "#403c3d"
info_bg = "#59e1e3"
info_fg = "#fdf0ed"
good_bg = "#29d398"
good_fg = "#fdf0ed"
warning_bg = "#fadad1"
warning_fg = "#fdf0ed"
critical_bg = "#e95678"
critical_fg = "#fdf0ed"
# The rest of the theme settings are left at default.
