# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Catppuccin Frappe by https://github.com/catppuccin/catppuccin

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#303446"
idle_fg = "#c6d0f5"
info_bg = "#81c8be"
info_fg = "#303446"
good_bg = "#a6d189"
good_fg = "#303446"
warning_bg = "#e5c890"
warning_fg = "#303446"
critical_bg = "#e78284"
critical_fg = "#303446"
# The rest of the theme settings are left at default.
