# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Tokyodark by Tiagovla (https://github.com/tiagovla/)

idle_bg = "#11121d"
idle_fg = "#abb2bf"
info_bg = "#a485dd"
info_fg = "#11121d"
good_bg = "#d7a65f"
good_fg = "#11121d"
warning_bg = "#7199ee"
warning_fg = "#11121d"
critical_bg = "#a485dd"
critical_fg = "#11121d"
# The rest of the theme settings are left at default.
