# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Jabuti by https://github.com/notusknot

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#292a37"
idle_fg = "#c0cbe3"
info_bg = "#ff7eb6"
info_fg = "#292a37"
good_bg = "#3fdaa4"
good_fg = "#292a37"
warning_bg = "#e1c697"
warning_fg = "#292a37"
critical_bg = "#ec6a88"
critical_fg = "#292a37"
# The rest of the theme settings are left at default.
