# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Material Lighter by Nate Peterson

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#fafafa"
idle_fg = "#80cbc4"
info_bg = "#39adb5"
info_fg = "#fafafa"
good_bg = "#91b859"
good_fg = "#fafafa"
warning_bg = "#ffb62c"
warning_fg = "#fafafa"
critical_bg = "#ff5370"
critical_fg = "#fafafa"
# The rest of the theme settings are left at default.
