# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Solar Flare Light by Chuck Harmston (https://chuck.harmston.ch)

idle_bg = "#f5f7fa"
idle_fg = "#586875"
info_bg = "#52cbb0"
info_fg = "#f5f7fa"
good_bg = "#7cc844"
good_fg = "#f5f7fa"
warning_bg = "#e4b51c"
warning_fg = "#f5f7fa"
critical_bg = "#ef5253"
critical_fg = "#f5f7fa"
# The rest of the theme settings are left at default.
