# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Tokyo Night Terminal Dark by Michaël Ball

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#16161e"
idle_fg = "#787c99"
info_bg = "#7dcfff"
info_fg = "#16161e"
good_bg = "#41a6b5"
good_fg = "#16161e"
warning_bg = "#e0af68"
warning_fg = "#16161e"
critical_bg = "#f7768e"
critical_fg = "#16161e"
# The rest of the theme settings are left at default.
