# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Summerfruit Dark by Christopher Corley (http://christop.club/)

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#151515"
idle_fg = "#d0d0d0"
info_bg = "#1faaaa"
info_fg = "#151515"
good_bg = "#00c918"
good_fg = "#151515"
warning_bg = "#aba800"
warning_fg = "#151515"
critical_bg = "#ff0086"
critical_fg = "#151515"
# The rest of the theme settings are left at default.
