# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Heetch Dark by Geoffrey Teale (tealeg@gmail.com)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#190134"
idle_fg = "#bdb6c5"
info_bg = "#f80059"
info_fg = "#190134"
good_bg = "#c33678"
good_fg = "#190134"
warning_bg = "#8f6c97"
warning_fg = "#190134"
critical_bg = "#27d9d5"
critical_fg = "#190134"
# The rest of the theme settings are left at default.
