# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Da One White by NNB (https://github.com/NNBnh)

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#ffffff"
idle_fg = "#181818"
info_bg = "#64b5a7"
info_fg = "#ffffff"
good_bg = "#76a85d"
good_fg = "#ffffff"
warning_bg = "#b3684f"
warning_fg = "#ffffff"
critical_bg = "#de5d6e"
critical_fg = "#ffffff"
# The rest of the theme settings are left at default.
