# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Dracula by Jamy Golden (http://github.com/JamyGolden), based on Dracula Theme (http://github.com/dracula)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#282a36"
idle_fg = "#f8f8f2"
info_bg = "#8be9fd"
info_fg = "#282a36"
good_bg = "#50fa7b"
good_fg = "#282a36"
warning_bg = "#f1fa8c"
warning_fg = "#282a36"
critical_bg = "#ff5555"
critical_fg = "#282a36"
# The rest of the theme settings are left at default.
