# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Ayu Mirage by Khue Nguyen &lt;Z5483Y@gmail.com&gt;

idle_bg = "#171b24"
idle_fg = "#cccac2"
info_bg = "#95e6cb"
info_fg = "#171b24"
good_bg = "#d5ff80"
good_fg = "#171b24"
warning_bg = "#ffd173"
warning_fg = "#171b24"
critical_bg = "#f28779"
critical_fg = "#171b24"
# The rest of the theme settings are left at default.
