# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Cupcake by Chris Kempson (http://chriskempson.com)

idle_bg = "#fbf1f2"
idle_fg = "#8b8198"
info_bg = "#69a9a7"
info_fg = "#fbf1f2"
good_bg = "#a3b367"
good_fg = "#fbf1f2"
warning_bg = "#dcb16c"
warning_fg = "#fbf1f2"
critical_bg = "#d57e85"
critical_fg = "#fbf1f2"
# The rest of the theme settings are left at default.
