# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# DanQing by Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#2d302f"
idle_fg = "#e0f0ef"
info_bg = "#30dff3"
info_fg = "#2d302f"
good_bg = "#8ab361"
good_fg = "#2d302f"
warning_bg = "#f0c239"
warning_fg = "#2d302f"
critical_bg = "#f9906f"
critical_fg = "#2d302f"
# The rest of the theme settings are left at default.
