# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Everforest by Sainnhe Park (https://github.com/sainnhe)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#2d353b"
idle_fg = "#d3c6aa"
info_bg = "#83c092"
info_fg = "#2d353b"
good_bg = "#a7c080"
good_fg = "#2d353b"
warning_bg = "#dbbc7f"
warning_fg = "#2d353b"
critical_bg = "#e67e80"
critical_fg = "#2d353b"
# The rest of the theme settings are left at default.
