# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Precious Light White by 4lex4 &lt;4lex49@zoho.com&gt;

[theme]
name = "custom_theme"
[theme.overrides]
idle_bg = "#ffffff"
idle_fg = "#555555"
info_bg = "#087767"
info_fg = "#ffffff"
good_bg = "#557301"
good_fg = "#ffffff"
warning_bg = "#876500"
warning_fg = "#ffffff"
critical_bg = "#af4947"
critical_fg = "#ffffff"
# The rest of the theme settings are left at default.
