# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# DanQing Light by Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)

idle_bg = "#fcfefd"
idle_fg = "#5a605d"
info_bg = "#30dff3"
info_fg = "#fcfefd"
good_bg = "#8ab361"
good_fg = "#fcfefd"
warning_bg = "#f0c239"
warning_fg = "#fcfefd"
critical_bg = "#f9906f"
critical_fg = "#fcfefd"
# The rest of the theme settings are left at default.
