# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Brush Trees by Abraham White &lt;abelincoln.white@gmail.com&gt;

idle_bg = "#e3efef"
idle_fg = "#6d828e"
info_bg = "#86b3b3"
info_fg = "#e3efef"
good_bg = "#87b386"
good_fg = "#e3efef"
warning_bg = "#aab386"
warning_fg = "#e3efef"
critical_bg = "#b38686"
critical_fg = "#e3efef"
# The rest of the theme settings are left at default.
