# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Embers by Jannik Siebert (https://github.com/janniks)

idle_bg = "#16130f"
idle_fg = "#a39a90"
info_bg = "#576d82"
info_fg = "#16130f"
good_bg = "#57826d"
good_fg = "#16130f"
warning_bg = "#6d8257"
warning_fg = "#16130f"
critical_bg = "#826d57"
critical_fg = "#16130f"
# The rest of the theme settings are left at default.
